### ISSUE TITLE
get a ValueError: Cannot feed value of shape

### ISSUE THREAD

**Issue by koolou** [ShafeenTejani/fast-style-transfer#4]
Hi Shafeen Tejani,
run trainning at win10 python3.6, and change some code for py3.6, u can get it this [link ](https://drive.google.com/a/giveyoupower.com/file/d/0B-VVe1ktD0TYMXB5QmZDaV9wOXc/view?usp=sharing), but  got a  ValueError ,detail:
ValueError: Cannot feed value of shape (1, 256, 256, 3) for Tensor 'input_batch:0', which has shape '(3, 256, 256, 3)'

Traceback (most recent call last):
  File "train_network.py", line 148, in <module>
    main()
  File "train_network.py", line 129, in main
    checkpoint_iterations=options.checkpoint_iterations
  File "C:\fast-style-transfer-master\fast_style_transfer.py", line 140, in train
    train_step.run(feed_dict={self.input_batch:batch})
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1706, in run
    _run_using_default_session(self, feed_dict, self.graph, session)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3963, in _run_using_default_session
    session.run(operation, feed_dict)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\ProgramData\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 975, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 256, 256, 3) for Tensor 'input_batch:0', which has shape '(3, 256, 256, 3)'``

**Comment by Banana1530** [comment]
In the fast_style_tranfer.py file, modify the code as follow: 



              for epoch in range(epochs):
                for i in range(0, len(content_training_images), self.batch_size):
                    print_progress(iterations)

                    batch = self._load_batch(content_training_images[i: i+self.batch_size])


                   ## Add code here###
                   if len(batch) != self.batch_size:
                            continue
                   ## End added code###


                    train_step.run(feed_dict={self.input_batch:batch})
                    
                    if is_checkpoint_iteration(iterations):
                        yield (
                            iterations,
                            sess,
                            self.stylized_image.eval(feed_dict={self.input_batch:batch})[0],
                            self._current_loss({self.input_batch:batch})
                       )
                    iterations += 1
