### ISSUE TITLE
ValueError: Dimensions must be equal

### ISSUE THREAD

**Issue by falrec** [ShafeenTejani/fast-style-transfer#6]
trying to run stylize on a centos7 box, returning the following. Initially thought it was the previously closed issue where dimensions had to be divisible by 4, so I changed the dimensions accordingly.  Doesn't seem to be the case. Any idea as to why this is happening?

Traceback (most recent call last):
  File "fast-style-transfer-master/stylize_image.py", line 77, in <module>
    main()
  File "fast-style-transfer-master/stylize_image.py", line 54, in main
    prediction = ffwd(reshaped_content_image, network)
  File "fast-style-transfer-master/stylize_image.py", line 63, in ffwd
    network = transform.net(img_placeholder)
  File "/home/murray/fast-style-transfer-master/transform.py", line 21, in net
    output = image + preds
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 894, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 183, in add
    "Add", x=x, y=y, name=name)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2958, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2209, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2159, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 627, in call_cpp_shape_fn
    require_shape_fn)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 691, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 12 and 3 for 'add_37' (op: 'Add') with input shapes: [1,960,960,12], [1,960,960,3].

**Comment by quietcricket** [comment]
Same problem here.

**Comment by chenchao666** [comment]
Have you solved it. I came across the same problem as you.
